name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Trigger workflow on push to the 'master' branch
  pull_request:
    branches:
      - master # Trigger workflow on pull requests targeting 'master'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH (git pull)
        uses: appleboy/ssh-action@v0.1.12
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 4345
          script: |
            cd /home/peyas/slimtest
            git pull origin master
